
import __ASTRO_IMAGE_IMPORT_Z1lvnHN from "/src/images/1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F1.md";
import __ASTRO_IMAGE_IMPORT_1uSwln from "/src/images/10.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F10.md";
import __ASTRO_IMAGE_IMPORT_1pD5sY from "/src/images/10.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F10.md";
import __ASTRO_IMAGE_IMPORT_ZRQ8dR from "/src/images/2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F2.md";
import __ASTRO_IMAGE_IMPORT_Z2dmUg3 from "/src/images/3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F3.md";
import __ASTRO_IMAGE_IMPORT_Z6H77H from "/src/images/4.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F4.md";
import __ASTRO_IMAGE_IMPORT_1YWG0D from "/src/images/5.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F5.md";
import __ASTRO_IMAGE_IMPORT_ZXyDEW from "/src/images/6.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F6.md";
import __ASTRO_IMAGE_IMPORT_1869so from "/src/images/7.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F7.md";
import __ASTRO_IMAGE_IMPORT_Z1Pqbdc from "/src/images/8.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F8.md";
import __ASTRO_IMAGE_IMPORT_Z1UuyMl from "/src/images/9.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F10.md";
import __ASTRO_IMAGE_IMPORT_Z2gBeiL from "/src/images/9.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F9+copy.md";
import __ASTRO_IMAGE_IMPORT_geBU9 from "/src/images/9.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F9.md";
export default new Map([["/src/images/1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F1.md", __ASTRO_IMAGE_IMPORT_Z1lvnHN], ["/src/images/10.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F10.md", __ASTRO_IMAGE_IMPORT_1uSwln], ["/src/images/10.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F10.md", __ASTRO_IMAGE_IMPORT_1pD5sY], ["/src/images/2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F2.md", __ASTRO_IMAGE_IMPORT_ZRQ8dR], ["/src/images/3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F3.md", __ASTRO_IMAGE_IMPORT_Z2dmUg3], ["/src/images/4.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F4.md", __ASTRO_IMAGE_IMPORT_Z6H77H], ["/src/images/5.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F5.md", __ASTRO_IMAGE_IMPORT_1YWG0D], ["/src/images/6.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F6.md", __ASTRO_IMAGE_IMPORT_ZXyDEW], ["/src/images/7.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F7.md", __ASTRO_IMAGE_IMPORT_1869so], ["/src/images/8.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F8.md", __ASTRO_IMAGE_IMPORT_Z1Pqbdc], ["/src/images/9.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F10.md", __ASTRO_IMAGE_IMPORT_Z1UuyMl], ["/src/images/9.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F9+copy.md", __ASTRO_IMAGE_IMPORT_Z2gBeiL], ["/src/images/9.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F9.md", __ASTRO_IMAGE_IMPORT_geBU9]]);
		